### ISSUE TITLE
Purchasing external equipment

### ISSUE THREAD

**Issue by cardi001** [bradley-evans/sdr-remote-monitor#2]
@Bradley Did you have a chance to look over what antenna we should purchase? If we have a larger budget for the antenna does that change your choice? Perhaps we should propose two antennas; one of them being marked as preferable, but more expensive.

@All Also, now that we don't have to design for field deployment, do we still need to avoid spin-able disks for our storage needs? I think we could get by with traditional HDDs; however, I do admit having the faster solid state drives would be nice, especially if we find ourselves needing to write to disk at an unexpectedly fast rate. Note, a single USRP 2920 has a maximum sample rate of 50MS/s (50MB/s) I think even if we used a normal drive we would be fine as long as we used a USB 3.0 or SATA connection. 
SSDs don't get full speeds with USB 2 anyway, so I think the main point is that whatever drive we use, has to be connected through USB 2.0 or SATA.
If we are being economical, I think we should choose a 2TB HDD. We can get them for less than a hundred dollars and not have to worry about space for our design. If we choose a 1TB SDD, it would be faster over the same connection, but cost over $380. 
If the funding is there, then we can just make our lives less worrisome and request for the SDD. 

I know that Dr. Liang wanted us to come up with a list of things we need to buy and email them to him or the post-doc this week. 

Links:
https://askubuntu.com/questions/41397/external-usb-hard-drives-what-speeds-should-be-expected
http://www.tomsguide.com/answers/id-2656423/average-hdd-read-write-speed.html
External SSD over USB 2:
https://arstechnica.com/civis/viewtopic.php?f=19&t=1281653

**Comment by bradley-evans** [comment]
@cardi001 The NAVSEA people seem to think they can provide a tactical antenna.
Example: https://www.american-milspec.com/p-5819-harris-prc-117f-prc-150-rf-5800-etc-vhf-blade-whip-antenna-and-goose-neck-un-used-10012-0202-rev-a-10512-0201-01.aspx

Otherwise I'll investigate what RF cable + antenna we'll need, probabaly something simple. I have a test set that goes with my own SDR, we can check and see if one of those are suitable, too.
